### ISSUE TITLE
能完善一个鸿蒙版本的么？

### ISSUE THREAD

**Issue by 100admin** [JeffMony/JeffVideoCache#5]
能完善一个鸿蒙版本的么？

**Comment by 100admin** [comment]
W/System.err: java.net.SocketException: Socket Shutdown
        at com.mytoutou.video.videocache.socket.request.HttpRequest.parseRequest(HttpRequest.java:64)
W/System.err:     at com.mytoutou.video.videocache.socket.SocketProcessTask.run(SocketProcessTask.java:44)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:929)

**Comment by JeffMony** [comment]
> W/System.err: java.net.SocketException: Socket Shutdown
> at com.mytoutou.video.videocache.socket.request.HttpRequest.parseRequest(HttpRequest.java:64)
> W/System.err: at com.mytoutou.video.videocache.socket.SocketProcessTask.run(SocketProcessTask.java:44)
> at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
> at java.util.concurrent.FutureTask.run(FutureTask.java:266)
> at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
> W/System.err: at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
> at java.lang.Thread.run(Thread.java:929)

你访问的具体url是什么啊
